### ISSUE TITLE
How can I help the project? Is he alive?

### ISSUE THREAD

**Issue by akuz0** [elauqsap/wireguard-cloud-vpn#3]
Good afternoon. I'm wondering how and how can I help you? I started to get interested in this topic and want to promote it (as part of student work). what stage are you at now? Where help is needed.

Also, can you tell me where you started? Or additional material, since this is interesting to me

**Comment by elauqsap** [comment]
Hello, you are free to fork but the direction I went leverages tailscale rather than doing all the wireguard configs myself. Plus it has some features that are more appealing than raw wireguard. Good luck!
